---
title: "RADR Code and Output"
author: Generated by BlueSky Statistics, LLC
date: "Thu Oct 01 2026 8:38:39 PM" 
output:
  html_document: default
R Version: 4.1.3
WE EXPECT USERS TO WANT TO RUN AND INSPECT THE OUTPUT CHUNK BY CHUNK, HERE WE WILL SHOW YOU TEXT OUTPUT IN THE R CONSOLE WINDOW WITH EACH CHUNK. YOU MAY NEED TO CHANGE YOUR STUDIO SETTINGS, SEE 1 BELOW
1. TO RUN ONE CHUNK AT A TIME AND SEE TEXT OUTPUT IN THE R CONSOLE SET THE OPTION IN THE RSTUDIO SETTINGS TO "CHUNK OUTPUT IN CONSOLE", YOU MUST ALSO UNCOMMENT LINE 60 BSky.print.text('rst') AND COMMENT BOTH LINE 61 BSky.print.html() AND LINE 62 BSky.print.text('rprint').
2. TO KNIT THE MARKDOWN FILE YOU MUST UNCOMMENT LINE 61 BSky.print.html() AND COMMENT LINE 62 BSky.print.text('rprint') AND LINE 60 BSky.print.text('rst')
3. TO RUN ONE CHUNK AT A TIME AND SEE OUTPUT IN THE INLINE CHUNK WINDOW SET THE OPTION IN THE RSTUDIO SETTINGS TO "CHUNK OUTPUT INLINE", YOU MUST ALSO UNCOMMENT LINE 62 BSky.print.text('rprint') AND COMMENT BOTH LINE 61 BSky.print.html() AND LINE 60 BSky.print.text('rst').
PLEASE RESTART RSTUDIO AND CLEAR OUTPUT CHUNKS WHEN CHANGING THE ABOVE OPTIONS
BlueSkyStatistics Version: 10.3.4
---


```{r setup-libraries, echo= FALSE, eval= TRUE, include = FALSE}
library(plyr)
library(dplyr)
library(rmarkdown) 
library(kableExtra)
library(BlueSky)
library(gdata)
library(stringr)
library(openxlsx)
library(haven)
library(readr)
library(readxl)
library(data.table)
library(foreign)



# The folowing is needed if R Studio needs to Knit to PDF
#library(tinytex)
```

```{r setup-knitr-options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)

# Will keep the one single global graphics device open for all the code chunks 
#knitr::opts_knit$set(global.device = TRUE)

# Will output all the graphics - otherwise only the last graphics will be shown
knitr::opts_knit$set(fig.keep = 'all')

# To see the fully rendered output not the markup
knitr::opts_chunk$set(results='asis')

# Comment the above and un-comment the below to see the non rendered markup output
#knitr::opts_chunk$set(results="markup")
```

```{r BSky-config, eval= TRUE, include = FALSE}
        
#To flush internally all previously run BSkyFormat() output 
BSkyGetHoldFormatObjList()

# Sets up the default output styling parameters 
BSky.print.text('rst')
#BSky.print.html()
#BSky.print.text('rprint')

# Output Data cell - decimal points/engineering notation settings
#BSkySetDecimalDigitSetting(2)
#BSkySetEngNotationSetting(TRUE)
#BSkySetRound(TRUE)
#BSkySetPvalueDisplaySetting(FALSE)

# End of config set up 
```
# Open Dataset: Matchup_RADR_093026_2021_22Players

```{r}
BSkyloadDataset(fullpathfilename='C:/Users/UserAccount/Documents/Radr/Matchup RADR 093026.xlsx', filetype='XLSX', worksheetName="2021-22 Players", replace_ds=TRUE, load.missing=FALSE, csvHeader=TRUE, character.to.factor=TRUE, isBasketData=FALSE, trimSPSStrailing=FALSE, sepChar=',', deciChar='.', encoding="NULL", datasetName='Matchup_RADR_093026_2021_22Players')
BSkyLoadRefresh("Matchup_RADR_093026_2021_22Players")
```
# Open Dataset: Matchup_RADR_093026_2021_22Players

```{r}
BSkyloadDataset(fullpathfilename='C:/Users/UserAccount/Documents/Radr/Matchup RADR 093026.xlsx', filetype='XLSX', worksheetName="2021-22 Players", replace_ds=TRUE, load.missing=FALSE, csvHeader=TRUE, character.to.factor=TRUE, isBasketData=FALSE, trimSPSStrailing=FALSE, sepChar=',', deciChar='.', encoding="NULL", datasetName='Matchup_RADR_093026_2021_22Players')
BSkyLoadRefresh("Matchup_RADR_093026_2021_22Players")
```
# Open Dataset: Matchup_RADR_093026_2021_22Players

```{r}
BSkyloadDataset(fullpathfilename='C:/Users/UserAccount/Documents/Radr/Matchup RADR 093026.xlsx', filetype='XLSX', worksheetName="2021-22 Players", replace_ds=TRUE, load.missing=FALSE, csvHeader=TRUE, character.to.factor=TRUE, isBasketData=FALSE, trimSPSStrailing=FALSE, sepChar=',', deciChar='.', encoding="NULL", datasetName='Matchup_RADR_093026_2021_22Players')
BSkyLoadRefresh("Matchup_RADR_093026_2021_22Players")
```
# Explore variable(s)

```{r}

	
	require(psych)
	require(dplyr)
	require(nortest)
	require(ggplot2)
	require(ggthemes)
	require(qqplotr)

	var_list = NULL
	histPlot = NULL
	qqPlot = NULL
	
	
	cv <- function(x, na.rm = TRUE)  {
			sd(x, na.rm = na.rm)/mean(x, na.rm = na.rm)
	}
	
	modes <- function(x, na.rm = TRUE, max_display = 25) {
	  if(length(x) != length(unique(x))){
		x = x[!is.na(x)]
		ux <- unique(x)
		if(length(ux) > max_display){ 
			ux = ux[1:max_display]
			tab <- tabulate(match(x, ux))
			invisible(return(paste(paste(ux[tab == max(tab)], collapse=","),",...", sep="")))
		} else {
			tab <- tabulate(match(x, ux))
			invisible(return(paste(ux[tab == max(tab)], collapse=",")))
		}
	  } else {
		invisible(return(' '))
	  }
	}
	
	sdMeanCI <- function(x, na.rm = TRUE) {
		# Calculate the mean of the sample data
		mean_value = mean(x, na.rm = na.rm)
		 
		# Compute the size
		#n <- length(x)
		n = length(x[!is.na(x)])
		 
		# Compute the standard deviation
		standard_deviation = sd(x, na.rm = na.rm)
		 
		# Compute the standard error
		standard_error = standard_deviation / sqrt(n)
		alpha = 0.05
		degrees_of_freedom = n - 1
		t_score = qt(p=alpha/2, df=degrees_of_freedom,lower.tail=F)
		margin_error = t_score * standard_error
		 
		# Calculate the lower bound and upper bound
		lower_bound = mean_value - margin_error
		upper_bound = mean_value + margin_error
		
		CI_values = c(mean = mean_value, '95% lower bound' = lower_bound, '95% upper bound' = upper_bound)
		
		#Calculate the CI for SD
		lower_bound.sd = sqrt(n-1)*standard_deviation/sqrt(qchisq(1-alpha/2, df = n-1))
		upper_bound.sd = sqrt(n-1)*standard_deviation/sqrt(qchisq(alpha/2, df = n-1))
		
		CI_values = rbind(CI_values, c(sd = standard_deviation, '95% lower bound' = lower_bound.sd, '95% upper bound' = upper_bound.sd))
		
		dimnames(CI_values)[[2]] = c("", '95% lower bound', '95% upper bound')
		rownames(CI_values) = c("mean", "sd")
		
		invisible(return(CI_values))
	}
	
	var_list = list(Defensive.rating = Matchup_RADR_093026_2021_22Players$Defensive.rating)
	
	for(i in 1:length(var_list)){
		col = list(var_list[[i]])
		names(col) = names(var_list)[i]
		BSkyFormat(paste("Exploration of the variable:", names(col), "from dataset Matchup_RADR_093026_2021_22Players"))
		
		BSkySummaryStats(datasetName = 'Matchup_RADR_093026_2021_22Players',
							datasetColumnObjects = col ,
							stats = c(
							min=TRUE, 
							max=TRUE, 
							mean=TRUE, 
							median=TRUE, 
							sum=FALSE, 
							sd=TRUE, 
							stderror=TRUE, 
							skew=TRUE,
							mad=TRUE,
							kurtos=TRUE,
							iqr=TRUE, 
							quantiles=TRUE), 
							quantilesProbs = c(0, 0.25, 0.5, 0.75, 1), 
							maxsum = 60, 
							additionalStats = c('cv','var','modes'),
							long_table = FALSE) %>% 
										BSkyFormat(outputTableIndex = c(2,3), outputTableRenames = paste("Numerical Statistical Analysis for variable:", names(col)))
	
		
		if(is.numeric(var_list[[i]])){
			sdMeanCI(col[[1]]) %>%
			BSkyFormat(outputTableRenames = paste("Confidence Interval of mean and sd for variable:", names(col)))
		
			BSky_Shapiro_Wilk_normality_test(vars = c(names(col)), dataset = 'Matchup_RADR_093026_2021_22Players') %>%
					BSkyFormat(outputTableRenames = paste("Shapiro Wilk Test results for variable:", names(col)))

			nortest::ad.test(x=var_list[[i]]) %>%
					BSkyFormat(outputTableIndex = c(tableone=1), outputTableRenames = paste("Anderson-Darling Test results for variable:", names(col)))
		
			suppressWarnings(stats::ks.test(x=var_list[[i]], y="pnorm") %>% BSkyFormat(outputTableIndex = c(1), outputTableRenames = paste("Kolmogorov-Smirnov Test resusts for variable:", names(col))))
	
							histPlot = ggplot(data=Matchup_RADR_093026_2021_22Players, aes(x = col[[1]])) +
					geom_histogram(bins = 9, alpha=1,  fill ="#727272"  , aes(y =..density..)) +
					stat_function(fun = dnorm, args = list(mean = mean(var_list[[i]], na.rm = TRUE) , sd = sd(var_list[[i]], na.rm = TRUE)) , col = "#eaf820", size = 2) +
					labs(x=names(col), title= paste("Histogram for variable", names(col))) +
					xlab(names(col)) + 
					ylab("Density") + 
	theme_grey() + 
	theme(text=element_text(family="sans",
	face="plain",
	color="#000000",  size=12,
	hjust=0.5, vjust=0.5),
	plot.title=element_text(hjust=.5, size=18)) 

						suppressWarnings(plot(histPlot))
			qqPlot = ggplot(data=Matchup_RADR_093026_2021_22Players, aes(sample = col[[1]])) +
			stat_qq_point(distribution = "norm", detrend = FALSE) +
			stat_qq_line(detrend = FALSE) + 
			labs(x=names(col) , title= paste("Q-Q Plot for variable",names(col))) +
			xlab("Theoretical Quantiles") +
			ylab("Sample Quantiles") + 
	theme_grey() + 
	theme(text=element_text(family="sans",
	face="plain",
	color="#000000",  size=12,
	hjust=0.5, vjust=0.5),
	plot.title=element_text(hjust=.5, size=18)) 

			suppressWarnings(plot(qqPlot))
			
			BSkyGraphicsFormat(bSkyFormatAppRequest = FALSE, noOfGraphics= 2, isRmarkdownOutputOn = TRUE)
		}
	}
	

```
# Histogram

```{r}
## [Histogram]
require(ggplot2);
require(ggthemes);
ggplot(data=Matchup_RADR_093026_2021_22Players, aes(x=Defensive.rating)) +
	geom_histogram(   bins =9,alpha=1,  fill ="#727272"  ) +
	labs(x="Defensive.rating", title= "Histogram for variable Defensive.rating") +
	xlab("Defensive.rating") + 
	ylab("Counts") + 
	theme_grey() + 
	theme(text=element_text(family="sans",
	face="plain",
	color="#000000",  size=12,
	hjust=0.5, vjust=0.5),
	plot.title=element_text(hjust=.5, size=18))
```
# Box Plot

```{r}
## [Box Plot]
require(ggplot2);
require(ggthemes);
Matchup_RADR_093026_2021_22Players  %>% ggplot( aes(,y=Defensive.rating  )) +
	geom_boxplot( col ="#727272", alpha=1,) +
	labs(,y="Defensive.rating", title= "Boxplot for variable: Defensive.rating") +
	xlab("") + ylab("Defensive.rating") + 
	theme_grey() + 
	theme(text=element_text(family="sans",
	face="plain",
	color="#000000",  size=12,
	hjust=0.5, vjust=0.5),
	plot.title=element_text(hjust=.5, size=18))  

```
# Explore variable(s)

```{r}

	
	require(psych)
	require(dplyr)
	require(nortest)
	require(ggplot2)
	require(ggthemes)
	require(qqplotr)

	var_list = NULL
	histPlot = NULL
	qqPlot = NULL
	
	
	cv <- function(x, na.rm = TRUE)  {
			sd(x, na.rm = na.rm)/mean(x, na.rm = na.rm)
	}
	
	modes <- function(x, na.rm = TRUE, max_display = 25) {
	  if(length(x) != length(unique(x))){
		x = x[!is.na(x)]
		ux <- unique(x)
		if(length(ux) > max_display){ 
			ux = ux[1:max_display]
			tab <- tabulate(match(x, ux))
			invisible(return(paste(paste(ux[tab == max(tab)], collapse=","),",...", sep="")))
		} else {
			tab <- tabulate(match(x, ux))
			invisible(return(paste(ux[tab == max(tab)], collapse=",")))
		}
	  } else {
		invisible(return(' '))
	  }
	}
	
	sdMeanCI <- function(x, na.rm = TRUE) {
		# Calculate the mean of the sample data
		mean_value = mean(x, na.rm = na.rm)
		 
		# Compute the size
		#n <- length(x)
		n = length(x[!is.na(x)])
		 
		# Compute the standard deviation
		standard_deviation = sd(x, na.rm = na.rm)
		 
		# Compute the standard error
		standard_error = standard_deviation / sqrt(n)
		alpha = 0.05
		degrees_of_freedom = n - 1
		t_score = qt(p=alpha/2, df=degrees_of_freedom,lower.tail=F)
		margin_error = t_score * standard_error
		 
		# Calculate the lower bound and upper bound
		lower_bound = mean_value - margin_error
		upper_bound = mean_value + margin_error
		
		CI_values = c(mean = mean_value, '95% lower bound' = lower_bound, '95% upper bound' = upper_bound)
		
		#Calculate the CI for SD
		lower_bound.sd = sqrt(n-1)*standard_deviation/sqrt(qchisq(1-alpha/2, df = n-1))
		upper_bound.sd = sqrt(n-1)*standard_deviation/sqrt(qchisq(alpha/2, df = n-1))
		
		CI_values = rbind(CI_values, c(sd = standard_deviation, '95% lower bound' = lower_bound.sd, '95% upper bound' = upper_bound.sd))
		
		dimnames(CI_values)[[2]] = c("", '95% lower bound', '95% upper bound')
		rownames(CI_values) = c("mean", "sd")
		
		invisible(return(CI_values))
	}
	
	var_list = list(matchup = Matchup_RADR_093026_2021_22Players$matchup)
	
	for(i in 1:length(var_list)){
		col = list(var_list[[i]])
		names(col) = names(var_list)[i]
		BSkyFormat(paste("Exploration of the variable:", names(col), "from dataset Matchup_RADR_093026_2021_22Players"))
		
		BSkySummaryStats(datasetName = 'Matchup_RADR_093026_2021_22Players',
							datasetColumnObjects = col ,
							stats = c(
							min=TRUE, 
							max=TRUE, 
							mean=TRUE, 
							median=TRUE, 
							sum=FALSE, 
							sd=TRUE, 
							stderror=TRUE, 
							skew=TRUE,
							mad=TRUE,
							kurtos=TRUE,
							iqr=TRUE, 
							quantiles=TRUE), 
							quantilesProbs = c(0, 0.25, 0.5, 0.75, 1), 
							maxsum = 60, 
							additionalStats = c('cv','var','modes'),
							long_table = FALSE) %>% 
										BSkyFormat(outputTableIndex = c(2,3), outputTableRenames = paste("Numerical Statistical Analysis for variable:", names(col)))
	
		
		if(is.numeric(var_list[[i]])){
			sdMeanCI(col[[1]]) %>%
			BSkyFormat(outputTableRenames = paste("Confidence Interval of mean and sd for variable:", names(col)))
		
			BSky_Shapiro_Wilk_normality_test(vars = c(names(col)), dataset = 'Matchup_RADR_093026_2021_22Players') %>%
					BSkyFormat(outputTableRenames = paste("Shapiro Wilk Test results for variable:", names(col)))

			nortest::ad.test(x=var_list[[i]]) %>%
					BSkyFormat(outputTableIndex = c(tableone=1), outputTableRenames = paste("Anderson-Darling Test results for variable:", names(col)))
		
			suppressWarnings(stats::ks.test(x=var_list[[i]], y="pnorm") %>% BSkyFormat(outputTableIndex = c(1), outputTableRenames = paste("Kolmogorov-Smirnov Test resusts for variable:", names(col))))
	
							histPlot = ggplot(data=Matchup_RADR_093026_2021_22Players, aes(x = col[[1]])) +
					geom_histogram(bins = 9, alpha=1,  fill ="#727272"  , aes(y =..density..)) +
					stat_function(fun = dnorm, args = list(mean = mean(var_list[[i]], na.rm = TRUE) , sd = sd(var_list[[i]], na.rm = TRUE)) , col = "#eaf820", size = 2) +
					labs(x=names(col), title= paste("Histogram for variable", names(col))) +
					xlab(names(col)) + 
					ylab("Density") + 
	theme_grey() + 
	theme(text=element_text(family="sans",
	face="plain",
	color="#000000",  size=12,
	hjust=0.5, vjust=0.5),
	plot.title=element_text(hjust=.5, size=18)) 

						suppressWarnings(plot(histPlot))
			qqPlot = ggplot(data=Matchup_RADR_093026_2021_22Players, aes(sample = col[[1]])) +
			stat_qq_point(distribution = "norm", detrend = FALSE) +
			stat_qq_line(detrend = FALSE) + 
			labs(x=names(col) , title= paste("Q-Q Plot for variable",names(col))) +
			xlab("Theoretical Quantiles") +
			ylab("Sample Quantiles") + 
	theme_grey() + 
	theme(text=element_text(family="sans",
	face="plain",
	color="#000000",  size=12,
	hjust=0.5, vjust=0.5),
	plot.title=element_text(hjust=.5, size=18)) 

			suppressWarnings(plot(qqPlot))
			
			BSkyGraphicsFormat(bSkyFormatAppRequest = FALSE, noOfGraphics= 2, isRmarkdownOutputOn = TRUE)
		}
	}
	

```
# Histogram

```{r}
## [Histogram]
require(ggplot2);
require(ggthemes);
ggplot(data=Matchup_RADR_093026_2021_22Players, aes(x=matchup)) +
	geom_histogram(   bins =9,alpha=1,  fill ="#727272"  ) +
	labs(x="matchup", title= "Histogram for variable matchup") +
	xlab("matchup") + 
	ylab("Counts") + 
	theme_grey() + 
	theme(text=element_text(family="sans",
	face="plain",
	color="#000000",  size=12,
	hjust=0.5, vjust=0.5),
	plot.title=element_text(hjust=.5, size=18))
```
# Box Plot

```{r}
## [Box Plot]
require(ggplot2);
require(ggthemes);
Matchup_RADR_093026_2021_22Players  %>% ggplot( aes(,y=matchup  )) +
	geom_boxplot( col ="#727272", alpha=1,) +
	labs(,y="matchup", title= "Boxplot for variable: matchup") +
	xlab("") + ylab("matchup") + 
	theme_grey() + 
	theme(text=element_text(family="sans",
	face="plain",
	color="#000000",  size=12,
	hjust=0.5, vjust=0.5),
	plot.title=element_text(hjust=.5, size=18))  

```
# Compute Variable

```{r}

require(stringr);
require(dplyr);

## support for design object. 
### backup current attributes if design object
isdesign = FALSE
backupattr = NULL
if(c("design") %in% class(Matchup_RADR_093026_2021_22Players))
{
    isdesign = TRUE
    dsattr = attributes(Matchup_RADR_093026_2021_22Players)
    # backup all except names and row.names because new col may get added 
    backupattr = dsattr[!(names(dsattr) %in% c("names", "row.names"))]
}

#Computes the new/existing column
local({tryCatch({ .GlobalEnv$Matchup_RADR_093026_2021_22Players <- Matchup_RADR_093026_2021_22Players %>% mutate( MatchupPerGame = matchup / Games.played  )}, error = function(e){  cat(conditionMessage(e))} )})

### restore design attributes
if(isdesign)
{
    attributes(Matchup_RADR_093026_2021_22Players) = c(attributes(Matchup_RADR_093026_2021_22Players), backupattr)
}

#Refresh the dataset in the data grid
BSkyLoadRefresh("Matchup_RADR_093026_2021_22Players")

```
# Histogram

```{r}
## [Histogram]
require(ggplot2);
require(ggthemes);
ggplot(data=Matchup_RADR_093026_2021_22Players, aes(x=MatchupPerGame)) +
	geom_histogram(   bins =9,alpha=1,  fill ="#727272"  ) +
	labs(x="MatchupPerGame", title= "Histogram for variable MatchupPerGame") +
	xlab("MatchupPerGame") + 
	ylab("Counts") + 
	theme_grey() + 
	theme(text=element_text(family="sans",
	face="plain",
	color="#000000",  size=12,
	hjust=0.5, vjust=0.5),
	plot.title=element_text(hjust=.5, size=18))
```
# Explore variable(s)

```{r}

	
	require(psych)
	require(dplyr)
	require(nortest)
	require(ggplot2)
	require(ggthemes)
	require(qqplotr)

	var_list = NULL
	histPlot = NULL
	qqPlot = NULL
	
	
	cv <- function(x, na.rm = TRUE)  {
			sd(x, na.rm = na.rm)/mean(x, na.rm = na.rm)
	}
	
	modes <- function(x, na.rm = TRUE, max_display = 25) {
	  if(length(x) != length(unique(x))){
		x = x[!is.na(x)]
		ux <- unique(x)
		if(length(ux) > max_display){ 
			ux = ux[1:max_display]
			tab <- tabulate(match(x, ux))
			invisible(return(paste(paste(ux[tab == max(tab)], collapse=","),",...", sep="")))
		} else {
			tab <- tabulate(match(x, ux))
			invisible(return(paste(ux[tab == max(tab)], collapse=",")))
		}
	  } else {
		invisible(return(' '))
	  }
	}
	
	sdMeanCI <- function(x, na.rm = TRUE) {
		# Calculate the mean of the sample data
		mean_value = mean(x, na.rm = na.rm)
		 
		# Compute the size
		#n <- length(x)
		n = length(x[!is.na(x)])
		 
		# Compute the standard deviation
		standard_deviation = sd(x, na.rm = na.rm)
		 
		# Compute the standard error
		standard_error = standard_deviation / sqrt(n)
		alpha = 0.05
		degrees_of_freedom = n - 1
		t_score = qt(p=alpha/2, df=degrees_of_freedom,lower.tail=F)
		margin_error = t_score * standard_error
		 
		# Calculate the lower bound and upper bound
		lower_bound = mean_value - margin_error
		upper_bound = mean_value + margin_error
		
		CI_values = c(mean = mean_value, '95% lower bound' = lower_bound, '95% upper bound' = upper_bound)
		
		#Calculate the CI for SD
		lower_bound.sd = sqrt(n-1)*standard_deviation/sqrt(qchisq(1-alpha/2, df = n-1))
		upper_bound.sd = sqrt(n-1)*standard_deviation/sqrt(qchisq(alpha/2, df = n-1))
		
		CI_values = rbind(CI_values, c(sd = standard_deviation, '95% lower bound' = lower_bound.sd, '95% upper bound' = upper_bound.sd))
		
		dimnames(CI_values)[[2]] = c("", '95% lower bound', '95% upper bound')
		rownames(CI_values) = c("mean", "sd")
		
		invisible(return(CI_values))
	}
	
	var_list = list(MatchupPerGame = Matchup_RADR_093026_2021_22Players$MatchupPerGame)
	
	for(i in 1:length(var_list)){
		col = list(var_list[[i]])
		names(col) = names(var_list)[i]
		BSkyFormat(paste("Exploration of the variable:", names(col), "from dataset Matchup_RADR_093026_2021_22Players"))
		
		BSkySummaryStats(datasetName = 'Matchup_RADR_093026_2021_22Players',
							datasetColumnObjects = col ,
							stats = c(
							min=TRUE, 
							max=TRUE, 
							mean=TRUE, 
							median=TRUE, 
							sum=FALSE, 
							sd=TRUE, 
							stderror=TRUE, 
							skew=TRUE,
							mad=TRUE,
							kurtos=TRUE,
							iqr=TRUE, 
							quantiles=TRUE), 
							quantilesProbs = c(0, 0.25, 0.5, 0.75, 1), 
							maxsum = 60, 
							additionalStats = c('cv','var','modes'),
							long_table = FALSE) %>% 
										BSkyFormat(outputTableIndex = c(2,3), outputTableRenames = paste("Numerical Statistical Analysis for variable:", names(col)))
	
		
		if(is.numeric(var_list[[i]])){
			sdMeanCI(col[[1]]) %>%
			BSkyFormat(outputTableRenames = paste("Confidence Interval of mean and sd for variable:", names(col)))
		
			BSky_Shapiro_Wilk_normality_test(vars = c(names(col)), dataset = 'Matchup_RADR_093026_2021_22Players') %>%
					BSkyFormat(outputTableRenames = paste("Shapiro Wilk Test results for variable:", names(col)))

			nortest::ad.test(x=var_list[[i]]) %>%
					BSkyFormat(outputTableIndex = c(tableone=1), outputTableRenames = paste("Anderson-Darling Test results for variable:", names(col)))
		
			suppressWarnings(stats::ks.test(x=var_list[[i]], y="pnorm") %>% BSkyFormat(outputTableIndex = c(1), outputTableRenames = paste("Kolmogorov-Smirnov Test resusts for variable:", names(col))))
	
							histPlot = ggplot(data=Matchup_RADR_093026_2021_22Players, aes(x = col[[1]])) +
					geom_histogram(bins = 9, alpha=1,  fill ="#727272"  , aes(y =..density..)) +
					stat_function(fun = dnorm, args = list(mean = mean(var_list[[i]], na.rm = TRUE) , sd = sd(var_list[[i]], na.rm = TRUE)) , col = "#eaf820", size = 2) +
					labs(x=names(col), title= paste("Histogram for variable", names(col))) +
					xlab(names(col)) + 
					ylab("Density") + 
	theme_grey() + 
	theme(text=element_text(family="sans",
	face="plain",
	color="#000000",  size=12,
	hjust=0.5, vjust=0.5),
	plot.title=element_text(hjust=.5, size=18)) 

						suppressWarnings(plot(histPlot))
			qqPlot = ggplot(data=Matchup_RADR_093026_2021_22Players, aes(sample = col[[1]])) +
			stat_qq_point(distribution = "norm", detrend = FALSE) +
			stat_qq_line(detrend = FALSE) + 
			labs(x=names(col) , title= paste("Q-Q Plot for variable",names(col))) +
			xlab("Theoretical Quantiles") +
			ylab("Sample Quantiles") + 
	theme_grey() + 
	theme(text=element_text(family="sans",
	face="plain",
	color="#000000",  size=12,
	hjust=0.5, vjust=0.5),
	plot.title=element_text(hjust=.5, size=18)) 

			suppressWarnings(plot(qqPlot))
			
			BSkyGraphicsFormat(bSkyFormatAppRequest = FALSE, noOfGraphics= 2, isRmarkdownOutputOn = TRUE)
		}
	}
	

```
# Open Dataset: RADR_Data

```{r}
BSkyloadDataset(fullpathfilename='C:/Users/UserAccount/Documents/Radr/RADR_Data.csv', filetype='CSV', worksheetName=NULL, replace_ds=TRUE, load.missing=FALSE, csvHeader=TRUE, character.to.factor=TRUE, isBasketData=FALSE, trimSPSStrailing=FALSE, sepChar=',', deciChar='.', encoding=NULL, datasetName='RADR_Data')
BSkyLoadRefresh("RADR_Data")
```
